version: '3'

services:
  app:
    container-name: mentor-me-docker
    restart: always
    build: ./ #specify the directory of the Dockerfile
    ports:
      - "80:5000" #specify ports forwarding
    links:
      - mongo #link this service to the database service
    depends-on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

